-- 休暇種別列を VARCHAR(10) → VARCHAR(40) に拡張
-- 追加種別: 経弔休暇 / 産休育休 / 病欠
ALTER TABLE vacation_request
  MODIFY COLUMN vacation_type VARCHAR(40) NOT NULL
    COMMENT 'FULL|HALF_AM|HALF_PM|CONDOLENCE_OWN_MARRIAGE|CONDOLENCE_CHILD_MARRIAGE|CONDOLENCE_SPOUSE_BIRTH|CONDOLENCE_FUNERAL_1ST|CONDOLENCE_FUNERAL_2ND|MATERNITY_PRE|MATERNITY_POST|CHILDCARE_LEAVE|SICK_LEAVE';
